/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PhpStanConfig, StrictRules, Extensions, ImportedNeonPreservation, PreservedNeonBlock } from '../types';
import { getExtensionIncludeBasePath } from './phpstanExtensions';

/**
 * Renders a PhpStanConfig domain object into highly readable, correct phpstan.neon string.
 */
export function renderNeon(config: PhpStanConfig, presetName: string = 'Modern Web App'): string {
  const lines: string[] = [];
  const preservedParameterKeys = new Set(
    config.importedRawBlocks?.parameterBlocks.map((block) => block.key) ?? []
  );
  
  lines.push('# Generated by PHPStan Configurator by Lars Moelleken (voku)');
  lines.push('# Target: PHPStan 2.x');
  lines.push(`# Preset: ${presetName}`);
  lines.push('# This file intentionally avoids PHPStan 1.x-only configuration options.');
  lines.push('');

  // 1. Includes Section
  const includes: string[] = [];
  
  if (config.strictRules.bleedingEdge) {
    includes.push('phar://phpstan.phar/conf/bleedingEdge.neon');
  }

// Extensions
  const strategy = config.extensions.installationStrategy || 'hybrid';

  if (strategy === 'manual_includes' || strategy === 'hybrid') {
    if (config.extensions.selectedExtensions) {
      for (const ext of config.extensions.selectedExtensions) {
        if (ext.enabled) {
          for (const file of ext.selectedIncludes) {
            includes.push(`${getExtensionIncludeBasePath(ext.id)}/${file}`);
          }
        }
      }
    } else {
      // Fallback to legacy
      if (config.extensions.symfony) {
        includes.push('vendor/phpstan/phpstan-symfony/extension.neon');
        includes.push('vendor/phpstan/phpstan-symfony/rules.neon');
      }
      if (config.extensions.doctrine) {
        includes.push('vendor/phpstan/phpstan-doctrine/extension.neon');
        includes.push('vendor/phpstan/phpstan-doctrine/rules.neon');
      }
      if (config.extensions.larastan) {
        includes.push('vendor/larastan/larastan/extension.neon');
      }
    }
  }

  // Custom includes
  for (const inc of config.extensions.customIncludes) {
    if (inc.trim() && !includes.includes(inc)) {
      includes.push(inc.trim());
    }
  }

  // Baseline include
  if (config.baseline && config.baseline.path) {
    includes.push(config.baseline.path.trim());
  }

  if (includes.length > 0) {
    lines.push('includes:');
    for (const inc of includes) {
      lines.push(`    - ${inc}`);
    }
    lines.push('');
  }

  // 2. Parameters Section
  lines.push('parameters:');
  
  // Level
  if (!preservedParameterKeys.has('level')) {
    lines.push(`    level: ${config.level}`);
  }
  
  // Paths
  if (!preservedParameterKeys.has('paths') && config.paths && config.paths.length > 0) {
    lines.push('    paths:');
    for (const path of config.paths) {
      lines.push(`        - ${path}`);
    }
  }

  // Exclude Paths
  if (!preservedParameterKeys.has('excludePaths') && config.excludes && config.excludes.length > 0) {
    lines.push('    excludePaths:');
    for (const esc of config.excludes) {
      lines.push(`        - ${esc}`);
    }
  }

  // PHP Version
  if (!preservedParameterKeys.has('phpVersion') && config.phpVersion) {
    lines.push(`    phpVersion: ${config.phpVersion} # ${formatPhpVersion(config.phpVersion)}`);
  }

  // Bootstrap files
  if (!preservedParameterKeys.has('bootstrapFiles') && config.bootstrapFiles && config.bootstrapFiles.length > 0) {
    lines.push('    bootstrapFiles:');
    for (const bsf of config.bootstrapFiles) {
      lines.push(`        - ${bsf}`);
    }
  }

  // Autoload files
  if (!preservedParameterKeys.has('scanFiles') && config.autoloadFiles && config.autoloadFiles.length > 0) {
    lines.push('    scanFiles:');
    for (const alf of config.autoloadFiles) {
      lines.push(`        - ${alf}`);
    }
  }

  // Strict Toggles
  if (!preservedParameterKeys.has('treatPhpDocTypesAsCertain')) {
    lines.push(`    treatPhpDocTypesAsCertain: ${config.strictRules.treatPhpDocTypesAsCertain ? 'true' : 'false'}`);
  }
  
  if (!preservedParameterKeys.has('reportUnmatchedIgnoredErrors') && config.strictRules.reportUnmatchedIgnoredErrors !== undefined) {
    lines.push(`    reportUnmatchedIgnoredErrors: ${config.strictRules.reportUnmatchedIgnoredErrors ? 'true' : 'false'}`);
  }
  if (!preservedParameterKeys.has('reportIgnoresWithoutComments') && config.strictRules.reportIgnoresWithoutComments !== undefined) {
    lines.push(`    reportIgnoresWithoutComments: ${config.strictRules.reportIgnoresWithoutComments ? 'true' : 'false'}`);
  }
  if (
    !preservedParameterKeys.has('checkImplicitMixed')
    && 
    config.strictRules.checkImplicitMixed !== undefined
    && (config.strictRules.checkImplicitMixed || (config.level !== '10' && config.level !== 'max'))
  ) {
    lines.push(`    checkImplicitMixed: ${config.strictRules.checkImplicitMixed ? 'true' : 'false'}`);
  }
  if (!preservedParameterKeys.has('checkBenevolentUnionTypes') && config.strictRules.checkBenevolentUnionTypes !== undefined) {
    lines.push(`    checkBenevolentUnionTypes: ${config.strictRules.checkBenevolentUnionTypes ? 'true' : 'false'}`);
  }

  // voku/phpstan-rules custom parameters definition
  if (!preservedParameterKeys.has('voku') && config.extensions.vokuParameters) {
    const v = config.extensions.vokuParameters;
    lines.push('');
    lines.push('    voku:');
    lines.push(`        checkForAssignments: ${v.checkForAssignments ? 'true' : 'false'}`);
    lines.push(`        checkYodaConditions: ${v.checkYodaConditions ? 'true' : 'false'}`);
    if (v.classesNotInIfConditions && v.classesNotInIfConditions.length > 0) {
      lines.push('        classesNotInIfConditions:');
      for (const cls of v.classesNotInIfConditions) {
        if (cls.trim()) {
          lines.push(`            - ${cls.trim()}`);
        }
      }
    }
  }

  // sidz/phpstan-rules custom parameters definition
  if (!preservedParameterKeys.has('sidzIgnoreMagicNumbers') && !preservedParameterKeys.has('sidzIgnoreNumericStrings') && config.extensions.sidzParameters) {
    const s = config.extensions.sidzParameters;
    lines.push('');
    lines.push('    # sidz/phpstan-rules magic numbers detection parameters');
    lines.push('    sidzIgnoreMagicNumbers:');
    if (s.ignoreMagicNumbers && s.ignoreMagicNumbers.length > 0) {
      for (const num of s.ignoreMagicNumbers) {
        lines.push(`        - ${num}`);
      }
    } else {
      lines.push('        []');
    }
    lines.push(`    sidzIgnoreNumericStrings: ${s.ignoreNumericStrings ? 'true' : 'false'}`);
  }

  for (const block of config.importedRawBlocks?.parameterBlocks ?? []) {
    lines.push('');
    lines.push(...block.lines);
  }

  for (const block of config.importedRawBlocks?.topLevelBlocks ?? []) {
    lines.push('');
    lines.push(...block.lines);
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

/**
 * Format internal version number (e.g., 80300) into readable string (e.g., "8.3")
 */
export function formatPhpVersion(versionCode: string): string {
  const num = parseInt(versionCode, 10);
  if (isNaN(num)) return versionCode;
  
  const major = Math.floor(num / 10000);
  const minor = Math.floor((num % 10000) / 100);
  const patch = num % 100;
  
  return `${major}.${minor}${patch > 0 ? '.' + patch : ''}`;
}

/**
 * Attempts to parse raw neon string into PhpStanConfig state.
 * Uses a heuristic Regex / string-split parser robust to incomplete or custom inputs.
 */
function stripNeonComments(line: string): string {
  let inSingleQuote = false;
  let inDoubleQuote = false;

  for (let i = 0; i < line.length; i += 1) {
    const char = line[i];
    const prev = i > 0 ? line[i - 1] : '';

    if (char === "'" && !inDoubleQuote && prev !== '\\') {
      inSingleQuote = !inSingleQuote;
      continue;
    }

    if (char === '"' && !inSingleQuote && prev !== '\\') {
      inDoubleQuote = !inDoubleQuote;
      continue;
    }

    if (char === '#' && !inSingleQuote && !inDoubleQuote) {
      return line.slice(0, i);
    }
  }

  return line;
}

function getIndent(line: string): number {
  return line.length - line.trimStart().length;
}

function sanitizeNeonValue(value: string): string {
  return value.trim().replace(/^['"]|['"]$/g, '');
}

function parseKeyValue(line: string): { key: string; value: string } | null {
  const cleanLine = stripNeonComments(line).trim();
  const colonIndex = cleanLine.indexOf(':');

  if (colonIndex === -1) {
    return null;
  }

  return {
    key: cleanLine.slice(0, colonIndex).trim(),
    value: cleanLine.slice(colonIndex + 1).trim(),
  };
}

function splitBlocks(lines: string[]): PreservedNeonBlock[] {
  const blocks: PreservedNeonBlock[] = [];
  let siblingIndent: number | null = null;
  let pendingLines: string[] = [];
  let currentBlock: PreservedNeonBlock | null = null;

  for (const line of lines) {
    const trimmed = stripNeonComments(line).trim();

    if (!trimmed) {
      if (currentBlock) {
        currentBlock.lines.push(line);
      } else {
        pendingLines.push(line);
      }
      continue;
    }

    const indent = getIndent(line);
    if (siblingIndent === null) {
      siblingIndent = indent;
    }

    const parsed = parseKeyValue(line);
    const startsNewBlock = indent === siblingIndent && parsed !== null && !trimmed.startsWith('-');

    if (startsNewBlock) {
      if (currentBlock) {
        blocks.push(currentBlock);
      }

      currentBlock = {
        key: parsed.key,
        lines: [...pendingLines, line],
      };
      pendingLines = [];
      continue;
    }

    if (currentBlock) {
      currentBlock.lines.push(line);
    } else {
      pendingLines.push(line);
    }
  }

  if (currentBlock) {
    blocks.push(currentBlock);
  }

  return blocks;
}

function normalizeBlockLines(block: PreservedNeonBlock): string[] {
  const firstKeyLineIndex = block.lines.findIndex((line) => parseKeyValue(line)?.key === block.key);

  return firstKeyLineIndex === -1 ? block.lines : block.lines.slice(firstKeyLineIndex);
}

function parseNeonListItems(blockLines: string[]): string[] | null {
  if (blockLines.length === 0) {
    return null;
  }

  const firstLine = parseKeyValue(blockLines[0]);
  if (!firstLine) {
    return null;
  }

  const items: string[] = [];
  const firstValue = firstLine.value;

  if (firstValue === '[]') {
    return [];
  }

  if (firstValue.startsWith('[') && firstValue.endsWith(']')) {
    return firstValue
      .slice(1, -1)
      .split(',')
      .map(item => sanitizeNeonValue(item))
      .filter(Boolean);
  }

  if (firstValue === '[') {
    for (const line of blockLines.slice(1)) {
      const trimmed = stripNeonComments(line).trim().replace(/,$/, '');
      if (!trimmed || trimmed === ']') {
        continue;
      }

      items.push(sanitizeNeonValue(trimmed));
    }

    return items;
  }

  if (firstValue !== '') {
    return null;
  }

  for (const line of blockLines.slice(1)) {
    const trimmed = stripNeonComments(line).trim();

    if (!trimmed) {
      continue;
    }

    if (!trimmed.startsWith('-')) {
      return null;
    }

    const value = sanitizeNeonValue(trimmed.slice(1));
    if (value) {
      items.push(value);
    }
  }

  return items;
}

function parseBooleanValue(line: string): boolean | undefined {
  const parsed = parseKeyValue(line);
  if (!parsed) {
    return undefined;
  }

  if (parsed.value === 'true') {
    return true;
  }

  if (parsed.value === 'false') {
    return false;
  }

  return undefined;
}

function parseVokuBlock(blockLines: string[]): Extensions['vokuParameters'] | null {
  const nestedBlocks = splitBlocks(blockLines.slice(1));
  let checkForAssignments = false;
  let checkYodaConditions = false;
  let classesNotInIfConditions: string[] = [];

  for (const block of nestedBlocks) {
    if (block.key === 'checkForAssignments') {
      const value = parseBooleanValue(block.lines[0]);
      if (value === undefined) {
        return null;
      }
      checkForAssignments = value;
      continue;
    }

    if (block.key === 'checkYodaConditions') {
      const value = parseBooleanValue(block.lines[0]);
      if (value === undefined) {
        return null;
      }
      checkYodaConditions = value;
      continue;
    }

    if (block.key === 'classesNotInIfConditions') {
      const items = parseNeonListItems(block.lines);
      if (items === null) {
        return null;
      }
      classesNotInIfConditions = items;
      continue;
    }

    return null;
  }

  return {
    checkForAssignments,
    checkYodaConditions,
    classesNotInIfConditions,
  };
}

function parseExcludePathsBlock(blockLines: string[]): string[] | null {
  const directItems = parseNeonListItems(blockLines);
  if (directItems !== null) {
    return directItems;
  }

  const nestedBlocks = splitBlocks(blockLines.slice(1));
  if (nestedBlocks.length === 0) {
    return null;
  }

  const items: string[] = [];

  for (const block of nestedBlocks) {
    if (block.key !== 'analyse' && block.key !== 'analyseAndScan') {
      return null;
    }

    const nestedItems = parseNeonListItems(normalizeBlockLines(block));
    if (nestedItems === null) {
      return null;
    }

    items.push(...nestedItems);
  }

  return items;
}

export function parseNeon(neonString: string): Partial<PhpStanConfig> {
  const result: Partial<PhpStanConfig> = {};
  const strictRules: Partial<StrictRules> = {};
  const extensions: Partial<Extensions> = {
    doctrine: false,
    symfony: false,
    larastan: false,
    customIncludes: []
  };
  const preservedBlocks: ImportedNeonPreservation = {
    parameterBlocks: [],
    topLevelBlocks: [],
  };

  const topLevelBlocks = splitBlocks(neonString.split('\n'));
  const listAccumulators: Record<string, string[]> = {
    paths: [],
    excludePaths: [],
    bootstrapFiles: [],
    scanFiles: [],
    includes: [],
    sidzIgnoreMagicNumbers: []
  };

  for (const block of topLevelBlocks) {
    const normalizedBlockLines = normalizeBlockLines(block);

    if (block.key === 'includes') {
      const includes = parseNeonListItems(normalizedBlockLines) ?? [];
      listAccumulators.includes.push(...includes);
      continue;
    }

    if (block.key !== 'parameters') {
      preservedBlocks.topLevelBlocks.push(block);
      continue;
    }

    const parameterBlocks = splitBlocks(normalizedBlockLines.slice(1));

    for (const parameterBlock of parameterBlocks) {
      const normalizedParameterLines = normalizeBlockLines(parameterBlock);
      const firstLine = parseKeyValue(normalizedParameterLines[0]);
      if (!firstLine) {
        preservedBlocks.parameterBlocks.push(parameterBlock);
        continue;
      }

      if (parameterBlock.key === 'level') {
        result.level = sanitizeNeonValue(firstLine.value);
        continue;
      }

      if (parameterBlock.key === 'phpVersion') {
        result.phpVersion = sanitizeNeonValue(firstLine.value);
        continue;
      }

      if (parameterBlock.key === 'targetVersion') {
        result.targetVersion = sanitizeNeonValue(firstLine.value) === '1.x' ? '1.x' : '2.x';
        continue;
      }

      if (parameterBlock.key === 'treatPhpDocTypesAsCertain') {
        strictRules.treatPhpDocTypesAsCertain = firstLine.value === 'true';
        continue;
      }

      if (parameterBlock.key === 'reportUnmatchedIgnoredErrors') {
        strictRules.reportUnmatchedIgnoredErrors = firstLine.value === 'true';
        continue;
      }

      if (parameterBlock.key === 'reportIgnoresWithoutComments') {
        strictRules.reportIgnoresWithoutComments = firstLine.value === 'true';
        continue;
      }

      if (parameterBlock.key === 'checkImplicitMixed') {
        strictRules.checkImplicitMixed = firstLine.value === 'true';
        continue;
      }

      if (parameterBlock.key === 'checkBenevolentUnionTypes') {
        strictRules.checkBenevolentUnionTypes = firstLine.value === 'true';
        continue;
      }

      if (parameterBlock.key === 'paths' || parameterBlock.key === 'bootstrapFiles' || parameterBlock.key === 'scanFiles') {
        const items = parseNeonListItems(normalizedParameterLines);
        if (items === null) {
          preservedBlocks.parameterBlocks.push(parameterBlock);
          continue;
        }

        listAccumulators[parameterBlock.key].push(...items);
        continue;
      }

      if (parameterBlock.key === 'excludePaths') {
        const items = parseExcludePathsBlock(normalizedParameterLines);
        if (items === null) {
          preservedBlocks.parameterBlocks.push(parameterBlock);
          continue;
        }

        listAccumulators.excludePaths.push(...items);
        continue;
      }

      if (parameterBlock.key === 'sidzIgnoreMagicNumbers') {
        const items = parseNeonListItems(normalizedParameterLines);
        if (items === null) {
          preservedBlocks.parameterBlocks.push(parameterBlock);
          continue;
        }

        listAccumulators.sidzIgnoreMagicNumbers.push(...items);
        continue;
      }

      if (parameterBlock.key === 'sidzIgnoreNumericStrings') {
        const value = parseBooleanValue(normalizedParameterLines[0]);
        if (value === undefined) {
          preservedBlocks.parameterBlocks.push(parameterBlock);
          continue;
        }

        extensions.sidzParameters = {
          ignoreMagicNumbers: [0, 1],
          ignoreNumericStrings: value,
          preset: 'ai_hardening'
        };
        continue;
      }

      if (parameterBlock.key === 'voku') {
        const vokuParameters = parseVokuBlock(normalizedParameterLines);
        if (!vokuParameters) {
          preservedBlocks.parameterBlocks.push(parameterBlock);
          continue;
        }

        extensions.vokuParameters = vokuParameters;
        continue;
      }

      preservedBlocks.parameterBlocks.push(parameterBlock);
    }
  }

  // Post-process includes to find extensions
  const customIncArr: string[] = [];
  let bleedingEdge = false;
  let hasBaseline = false;
  let baselinePath = '';

  const selectedExtsMap: Record<string, { enabled: boolean; selectedIncludes: string[] }> = {
    'strict-rules': { enabled: false, selectedIncludes: [] },
    'deprecation-rules': { enabled: false, selectedIncludes: [] },
    'doctrine': { enabled: false, selectedIncludes: [] },
    'symfony': { enabled: false, selectedIncludes: [] },
    'larastan': { enabled: false, selectedIncludes: [] },
    'phpunit': { enabled: false, selectedIncludes: [] },
    'voku-rules': { enabled: false, selectedIncludes: [] },
    'sidz-rules': { enabled: false, selectedIncludes: [] }
  };

  for (const inc of listAccumulators.includes) {
    if (inc.includes('bleedingEdge.neon')) {
      bleedingEdge = true;
    } else if (inc.includes('phpstan-strict-rules')) {
      selectedExtsMap['strict-rules'].enabled = true;
      if (inc.endsWith('rules.neon')) selectedExtsMap['strict-rules'].selectedIncludes.push('rules.neon');
    } else if (inc.includes('phpstan-deprecation-rules')) {
      selectedExtsMap['deprecation-rules'].enabled = true;
      if (inc.endsWith('rules.neon')) selectedExtsMap['deprecation-rules'].selectedIncludes.push('rules.neon');
    } else if (inc.includes('phpstan-symfony')) {
      extensions.symfony = true;
      selectedExtsMap['symfony'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['symfony'].selectedIncludes.push(filePart);
    } else if (inc.includes('phpstan-doctrine')) {
      extensions.doctrine = true;
      selectedExtsMap['doctrine'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['doctrine'].selectedIncludes.push(filePart);
    } else if (inc.includes('larastan')) {
      extensions.larastan = true;
      selectedExtsMap['larastan'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['larastan'].selectedIncludes.push(filePart);
    } else if (inc.includes('phpstan-phpunit')) {
      selectedExtsMap['phpunit'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['phpunit'].selectedIncludes.push(filePart);
    } else if (inc.includes('voku/phpstan-rules') || inc.includes('voku-rules')) {
      selectedExtsMap['voku-rules'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['voku-rules'].selectedIncludes.push(filePart);
    } else if (inc.includes('sidz/phpstan-rules') || inc.includes('sidz-rules')) {
      selectedExtsMap['sidz-rules'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['sidz-rules'].selectedIncludes.push(filePart);
    } else if (inc.toLowerCase().includes('baseline')) {
      hasBaseline = true;
      baselinePath = inc;
    } else if (inc) {
      customIncArr.push(inc);
    }
  }

  extensions.selectedExtensions = Object.keys(selectedExtsMap).map(id => ({
    id,
    enabled: selectedExtsMap[id].enabled,
    selectedIncludes: selectedExtsMap[id].selectedIncludes.length > 0
      ? Array.from(new Set(selectedExtsMap[id].selectedIncludes))
      : (id === 'voku-rules' || id === 'strict-rules' || id === 'deprecation-rules' || id === 'sidz-rules' ? ['rules.neon'] : ['extension.neon'])
  }));

  extensions.installationStrategy = 'manual_includes';
  extensions.customIncludes = customIncArr;
  extensions.vokuParameters ??= {
    checkForAssignments: false,
    checkYodaConditions: false,
    classesNotInIfConditions: []
  };

  const ignoreMagicNumbers = (listAccumulators['sidzIgnoreMagicNumbers'] || [])
    .map(val => parseFloat(val))
    .filter(n => !isNaN(n));

  extensions.sidzParameters = {
    ignoreMagicNumbers: ignoreMagicNumbers.length > 0 ? ignoreMagicNumbers : [0, 1],
    ignoreNumericStrings: extensions.sidzParameters?.ignoreNumericStrings ?? false,
    preset: ignoreMagicNumbers.some(n => ![0, 1].includes(n)) ? 'balanced' : 'ai_hardening'
  };

  // Build the strict rules
  result.strictRules = {
    treatPhpDocTypesAsCertain: strictRules.treatPhpDocTypesAsCertain ?? true,
    bleedingEdge,
    reportUnmatchedIgnoredErrors: strictRules.reportUnmatchedIgnoredErrors ?? true,
    reportIgnoresWithoutComments: strictRules.reportIgnoresWithoutComments ?? false,
    checkImplicitMixed: strictRules.checkImplicitMixed ?? false,
    checkBenevolentUnionTypes: strictRules.checkBenevolentUnionTypes ?? false,
  };

  result.extensions = extensions as Extensions;
  
  if (listAccumulators.paths.length > 0) {
    result.paths = listAccumulators.paths;
  }
  if (listAccumulators.excludePaths.length > 0) {
    result.excludes = listAccumulators.excludePaths;
  }
  if (listAccumulators.bootstrapFiles.length > 0) {
    result.bootstrapFiles = listAccumulators.bootstrapFiles;
  }
  if (listAccumulators.scanFiles.length > 0) {
    result.autoloadFiles = listAccumulators.scanFiles;
  }

  if (hasBaseline) {
    result.baseline = {
      path: baselinePath,
      generateIfMissing: false,
      warningAboutStale: true
    };
  } else {
    result.baseline = null;
  }

  if (preservedBlocks.parameterBlocks.length > 0 || preservedBlocks.topLevelBlocks.length > 0) {
    result.importedRawBlocks = preservedBlocks;
  }

  return result;
}
