/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PhpStanConfig, StrictRules, Extensions, BaselineConfig } from '../types';

/**
 * Renders a PhpStanConfig domain object into highly readable, correct phpstan.neon string.
 */
export function renderNeon(config: PhpStanConfig, presetName: string = 'Modern Web App'): string {
  const lines: string[] = [];
  
  lines.push('# Generated by PHPStan Configurator by Lars Moelleken (voku)');
  lines.push('# Target: PHPStan 2.x');
  lines.push(`# Preset: ${presetName}`);
  lines.push('# This file intentionally avoids PHPStan 1.x-only configuration options.');
  lines.push('');

  // 1. Includes Section
  const includes: string[] = [];
  
  if (config.strictRules.bleedingEdge) {
    includes.push('vendor/phpstan/phpstan/conf/bleedingEdge.neon');
  }

// Extensions
  const strategy = config.extensions.installationStrategy || 'hybrid';

  if (strategy === 'manual_includes' || strategy === 'hybrid') {
    if (config.extensions.selectedExtensions) {
      for (const ext of config.extensions.selectedExtensions) {
        if (ext.enabled) {
          for (const file of ext.selectedIncludes) {
            let pkg = `vendor/phpstan/phpstan-${ext.id}`;
            if (ext.id === 'larastan') {
              pkg = 'vendor/nunomaduro/larastan';
            } else if (ext.id === 'voku-rules') {
              pkg = 'vendor/voku/phpstan-rules';
            } else if (ext.id === 'sidz-rules') {
              pkg = 'vendor/sidz/phpstan-rules';
            }
            includes.push(`${pkg}/${file}`);
          }
        }
      }
    } else {
      // Fallback to legacy
      if (config.extensions.symfony) {
        includes.push('vendor/phpstan/phpstan-symfony/extension.neon');
        includes.push('vendor/phpstan/phpstan-symfony/rules.neon');
      }
      if (config.extensions.doctrine) {
        includes.push('vendor/phpstan/phpstan-doctrine/extension.neon');
        includes.push('vendor/phpstan/phpstan-doctrine/rules.neon');
      }
      if (config.extensions.larastan) {
        includes.push('vendor/nunomaduro/larastan/extension.neon');
      }
    }
  }

  // Custom includes
  for (const inc of config.extensions.customIncludes) {
    if (inc.trim() && !includes.includes(inc)) {
      includes.push(inc.trim());
    }
  }

  // Baseline include
  if (config.baseline && config.baseline.path) {
    includes.push(config.baseline.path.trim());
  }

  if (includes.length > 0) {
    lines.push('includes:');
    for (const inc of includes) {
      lines.push(`    - ${inc}`);
    }
    lines.push('');
  }

  // 2. Parameters Section
  lines.push('parameters:');
  
  // Level
  lines.push(`    level: ${config.level}`);
  
  // Paths
  if (config.paths && config.paths.length > 0) {
    lines.push('    paths:');
    for (const path of config.paths) {
      lines.push(`        - ${path}`);
    }
  }

  // Exclude Paths
  if (config.excludes && config.excludes.length > 0) {
    lines.push('    excludePaths:');
    for (const esc of config.excludes) {
      lines.push(`        - ${esc}`);
    }
  }

  // PHP Version
  if (config.phpVersion) {
    lines.push(`    phpVersion: ${config.phpVersion} # ${formatPhpVersion(config.phpVersion)}`);
  }

  // Bootstrap files
  if (config.bootstrapFiles && config.bootstrapFiles.length > 0) {
    lines.push('    bootstrapFiles:');
    for (const bsf of config.bootstrapFiles) {
      lines.push(`        - ${bsf}`);
    }
  }

  // Autoload files
  if (config.autoloadFiles && config.autoloadFiles.length > 0) {
    lines.push('    scanFiles:');
    for (const alf of config.autoloadFiles) {
      lines.push(`        - ${alf}`);
    }
  }

  // Strict Toggles
  lines.push(`    treatPhpDocTypesAsCertain: ${config.strictRules.treatPhpDocTypesAsCertain ? 'true' : 'false'}`);
  
  if (config.strictRules.reportUnmatchedIgnoredErrors !== undefined) {
    lines.push(`    reportUnmatchedIgnoredErrors: ${config.strictRules.reportUnmatchedIgnoredErrors ? 'true' : 'false'}`);
  }
  if (config.strictRules.reportIgnoresWithoutComments !== undefined) {
    lines.push(`    reportIgnoresWithoutComments: ${config.strictRules.reportIgnoresWithoutComments ? 'true' : 'false'}`);
  }
  if (
    config.strictRules.checkImplicitMixed !== undefined
    && (config.strictRules.checkImplicitMixed || (config.level !== '10' && config.level !== 'max'))
  ) {
    lines.push(`    checkImplicitMixed: ${config.strictRules.checkImplicitMixed ? 'true' : 'false'}`);
  }
  if (config.strictRules.checkBenevolentUnionTypes !== undefined) {
    lines.push(`    checkBenevolentUnionTypes: ${config.strictRules.checkBenevolentUnionTypes ? 'true' : 'false'}`);
  }

  // voku/phpstan-rules custom parameters definition
  if (config.extensions.vokuParameters) {
    const v = config.extensions.vokuParameters;
    lines.push('');
    lines.push('    voku:');
    lines.push(`        checkForAssignments: ${v.checkForAssignments ? 'true' : 'false'}`);
    lines.push(`        checkYodaConditions: ${v.checkYodaConditions ? 'true' : 'false'}`);
    if (v.classesNotInIfConditions && v.classesNotInIfConditions.length > 0) {
      lines.push('        classesNotInIfConditions:');
      for (const cls of v.classesNotInIfConditions) {
        if (cls.trim()) {
          lines.push(`            - ${cls.trim()}`);
        }
      }
    }
  }

  // sidz/phpstan-rules custom parameters definition
  if (config.extensions.sidzParameters) {
    const s = config.extensions.sidzParameters;
    lines.push('');
    lines.push('    # sidz/phpstan-rules magic numbers detection parameters');
    lines.push('    sidzIgnoreMagicNumbers:');
    if (s.ignoreMagicNumbers && s.ignoreMagicNumbers.length > 0) {
      for (const num of s.ignoreMagicNumbers) {
        lines.push(`        - ${num}`);
      }
    } else {
      lines.push('        []');
    }
    lines.push(`    sidzIgnoreNumericStrings: ${s.ignoreNumericStrings ? 'true' : 'false'}`);
  }

  return lines.join('\n');
}

/**
 * Format internal version number (e.g., 80300) into readable string (e.g., "8.3")
 */
export function formatPhpVersion(versionCode: string): string {
  const num = parseInt(versionCode, 10);
  if (isNaN(num)) return versionCode;
  
  const major = Math.floor(num / 10000);
  const minor = Math.floor((num % 10000) / 100);
  const patch = num % 100;
  
  return `${major}.${minor}${patch > 0 ? '.' + patch : ''}`;
}

/**
 * Attempts to parse raw neon string into PhpStanConfig state.
 * Uses a heuristic Regex / string-split parser robust to incomplete or custom inputs.
 */
export function parseNeon(neonString: string): Partial<PhpStanConfig> {
  const result: Partial<PhpStanConfig> = {};
  const strictRules: Partial<StrictRules> = {};
  const extensions: Partial<Extensions> = {
    doctrine: false,
    symfony: false,
    larastan: false,
    customIncludes: []
  };

  const lines = neonString.split('\n');
  
  let currentKey = '';
  const listAccumulators: Record<string, string[]> = {
    paths: [],
    excludePaths: [],
    bootstrapFiles: [],
    scanFiles: [],
    includes: [],
    sidzIgnoreMagicNumbers: []
  };

  for (const rawLine of lines) {
    // strip comments
    const lineWithoutComments = rawLine.split('#')[0];
    const trimmedLine = lineWithoutComments.trim();
    if (!trimmedLine) continue;

    // Is it a list item?
    if (trimmedLine.startsWith('-')) {
      const listVal = trimmedLine.substring(1).trim().replace(/['"]/g, '');
      if (listVal && currentKey) {
        if (listAccumulators[currentKey]) {
          listAccumulators[currentKey].push(listVal);
        }
      }
      continue;
    }

    // Key-value detection (e.g. key: val)
    const colonIndex = trimmedLine.indexOf(':');
    if (colonIndex !== -1) {
      const key = trimmedLine.substring(0, colonIndex).trim();
      const val = trimmedLine.substring(colonIndex + 1).trim().replace(/['"]/g, '');

      if (key === 'includes' || key === 'paths' || key === 'excludePaths' || key === 'bootstrapFiles' || key === 'scanFiles' || key === 'sidzIgnoreMagicNumbers') {
        currentKey = key;
        // Check if there is an inline bracket list e.g. [src, app]
        if (val.startsWith('[') && val.endsWith(']')) {
          const items = val.substring(1, val.length - 1).split(',').map(s => s.trim().replace(/['"]/g, ''));
          listAccumulators[key].push(...items);
        }
      } else {
        // scalar properties
        if (key === 'level') {
          result.level = val;
        } else if (key === 'phpVersion') {
          result.phpVersion = val;
        } else if (key === 'targetVersion') {
          result.targetVersion = val === '1.x' ? '1.x' : '2.x';
        } else if (key === 'treatPhpDocTypesAsCertain') {
          strictRules.treatPhpDocTypesAsCertain = val === 'true';
        } else if (key === 'reportUnmatchedIgnoredErrors') {
          strictRules.reportUnmatchedIgnoredErrors = val === 'true';
        } else if (key === 'reportIgnoresWithoutComments') {
          strictRules.reportIgnoresWithoutComments = val === 'true';
        } else if (key === 'checkImplicitMixed') {
          strictRules.checkImplicitMixed = val === 'true';
        } else if (key === 'checkBenevolentUnionTypes') {
          strictRules.checkBenevolentUnionTypes = val === 'true';
        }
      }
    }
  }

  // Post-process includes to find extensions
  const customIncArr: string[] = [];
  let bleedingEdge = false;
  let hasBaseline = false;
  let baselinePath = '';

  const selectedExtsMap: Record<string, { enabled: boolean; selectedIncludes: string[] }> = {
    'strict-rules': { enabled: false, selectedIncludes: [] },
    'deprecation-rules': { enabled: false, selectedIncludes: [] },
    'doctrine': { enabled: false, selectedIncludes: [] },
    'symfony': { enabled: false, selectedIncludes: [] },
    'larastan': { enabled: false, selectedIncludes: [] },
    'phpunit': { enabled: false, selectedIncludes: [] },
    'voku-rules': { enabled: false, selectedIncludes: [] },
    'sidz-rules': { enabled: false, selectedIncludes: [] }
  };

  for (const inc of listAccumulators.includes) {
    if (inc.includes('bleedingEdge.neon')) {
      bleedingEdge = true;
    } else if (inc.includes('phpstan-strict-rules')) {
      selectedExtsMap['strict-rules'].enabled = true;
      if (inc.endsWith('rules.neon')) selectedExtsMap['strict-rules'].selectedIncludes.push('rules.neon');
    } else if (inc.includes('phpstan-deprecation-rules')) {
      selectedExtsMap['deprecation-rules'].enabled = true;
      if (inc.endsWith('rules.neon')) selectedExtsMap['deprecation-rules'].selectedIncludes.push('rules.neon');
    } else if (inc.includes('phpstan-symfony')) {
      extensions.symfony = true;
      selectedExtsMap['symfony'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['symfony'].selectedIncludes.push(filePart);
    } else if (inc.includes('phpstan-doctrine')) {
      extensions.doctrine = true;
      selectedExtsMap['doctrine'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['doctrine'].selectedIncludes.push(filePart);
    } else if (inc.includes('larastan')) {
      extensions.larastan = true;
      selectedExtsMap['larastan'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['larastan'].selectedIncludes.push(filePart);
    } else if (inc.includes('phpstan-phpunit')) {
      selectedExtsMap['phpunit'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['phpunit'].selectedIncludes.push(filePart);
    } else if (inc.includes('voku/phpstan-rules') || inc.includes('voku-rules')) {
      selectedExtsMap['voku-rules'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['voku-rules'].selectedIncludes.push(filePart);
    } else if (inc.includes('sidz/phpstan-rules') || inc.includes('sidz-rules')) {
      selectedExtsMap['sidz-rules'].enabled = true;
      const filePart = inc.substring(inc.lastIndexOf('/') + 1);
      selectedExtsMap['sidz-rules'].selectedIncludes.push(filePart);
    } else if (inc.toLowerCase().includes('baseline')) {
      hasBaseline = true;
      baselinePath = inc;
    } else if (inc) {
      customIncArr.push(inc);
    }
  }

  extensions.selectedExtensions = Object.keys(selectedExtsMap).map(id => ({
    id,
    enabled: selectedExtsMap[id].enabled,
    selectedIncludes: selectedExtsMap[id].selectedIncludes.length > 0
      ? Array.from(new Set(selectedExtsMap[id].selectedIncludes))
      : (id === 'voku-rules' || id === 'strict-rules' || id === 'deprecation-rules' || id === 'sidz-rules' ? ['rules.neon'] : ['extension.neon'])
  }));

  extensions.installationStrategy = 'manual_includes';
  extensions.customIncludes = customIncArr;

  // Extract voku parameters
  let checkForAssignments = false;
  let checkYodaConditions = false;
  const classesNotInIfConditions: string[] = [];
  let inVokuClassesBlock = false;

  for (const line of lines) {
    const cleanLine = line.split('#')[0].trim();
    if (!cleanLine) continue;

    if (cleanLine.includes('checkForAssignments') && cleanLine.includes(':')) {
      checkForAssignments = cleanLine.split(':')[1].trim() === 'true';
    } else if (cleanLine.includes('checkYodaConditions') && cleanLine.includes(':')) {
      checkYodaConditions = cleanLine.split(':')[1].trim() === 'true';
    } else if (cleanLine.startsWith('classesNotInIfConditions:')) {
      inVokuClassesBlock = true;
    } else if (inVokuClassesBlock && cleanLine.startsWith('-')) {
      const val = cleanLine.substring(1).trim().replace(/['"]/g, '');
      if (val) {
        classesNotInIfConditions.push(val);
      }
    } else if (inVokuClassesBlock && cleanLine.includes(':')) {
      if (!cleanLine.startsWith('classesNotInIfConditions:')) {
        inVokuClassesBlock = false;
      }
    }
  }

  extensions.vokuParameters = {
    checkForAssignments,
    checkYodaConditions,
    classesNotInIfConditions
  };

  // Extract sidz parameters
  let ignoreNumericStrings = false;
  for (const line of lines) {
    const cleanLine = line.split('#')[0].trim();
    if (!cleanLine) continue;
    if (cleanLine.includes('sidzIgnoreNumericStrings') && cleanLine.includes(':')) {
      ignoreNumericStrings = cleanLine.split(':')[1].trim() === 'true';
    }
  }

  const ignoreMagicNumbers = (listAccumulators['sidzIgnoreMagicNumbers'] || [])
    .map(val => parseFloat(val))
    .filter(n => !isNaN(n));

  extensions.sidzParameters = {
    ignoreMagicNumbers: ignoreMagicNumbers.length > 0 ? ignoreMagicNumbers : [0, 1],
    ignoreNumericStrings,
    preset: ignoreMagicNumbers.some(n => ![0,1].includes(n)) ? 'balanced' : 'ai_hardening'
  };

  // Build the strict rules
  result.strictRules = {
    treatPhpDocTypesAsCertain: strictRules.treatPhpDocTypesAsCertain ?? true,
    bleedingEdge,
    reportUnmatchedIgnoredErrors: strictRules.reportUnmatchedIgnoredErrors ?? true,
    reportIgnoresWithoutComments: strictRules.reportIgnoresWithoutComments ?? false,
    checkImplicitMixed: strictRules.checkImplicitMixed ?? false,
    checkBenevolentUnionTypes: strictRules.checkBenevolentUnionTypes ?? false,
  };

  result.extensions = extensions as Extensions;
  
  if (listAccumulators.paths.length > 0) {
    result.paths = listAccumulators.paths;
  }
  if (listAccumulators.excludePaths.length > 0) {
    result.excludes = listAccumulators.excludePaths;
  }
  if (listAccumulators.bootstrapFiles.length > 0) {
    result.bootstrapFiles = listAccumulators.bootstrapFiles;
  }
  if (listAccumulators.scanFiles.length > 0) {
    result.autoloadFiles = listAccumulators.scanFiles;
  }

  if (hasBaseline) {
    result.baseline = {
      path: baselinePath,
      generateIfMissing: false,
      warningAboutStale: true
    };
  } else {
    result.baseline = null;
  }

  return result;
}
