/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file is generated by scripts/sync-phpstan-config-reference.mjs.
 * Do not edit manually.
 */

export interface PhpStanReferenceEntry {
  key: string;
  section: string;
  summary: string;
  defaultValue?: string;
  availableIn?: string;
}

export const PHPSTAN_CONFIG_REFERENCE_META = {
  ref: '2.2.x',
  sourceUrl: 'https://raw.githubusercontent.com/phpstan/phpstan/2.2.x/website/src/config-reference.md',
  sourceHash: '063c97f35607c24d0d62067c5bf54f9c21916b2ca69336435ba37fe993bf6fb0',
} as const;

export const PHPSTAN_CONFIG_REFERENCE = [
  {
    "key": "additionalConstructors",
    "section": "Miscellaneous parameters",
    "summary": "If you want to avoid errors caused by writing to readonly properties outside of constructors, configure additionalConstructors to specify methods to treat as constructors:",
    "defaultValue": "[]"
  },
  {
    "key": "bootstrapFiles",
    "section": "Bootstrap",
    "summary": "See PHPStan config reference section \"Bootstrap\"."
  },
  {
    "key": "cache.nameScopeMapMemoryCacheCountMax",
    "section": "Caching",
    "summary": "Maximum number of file name scope maps (namespace and import context) cached in memory. Used during PHPDoc resolution to look up the correct namespace and use statement context.",
    "defaultValue": "2048"
  },
  {
    "key": "cache.nodesByStringCountMax",
    "section": "Caching",
    "summary": "Maximum number of parsed PHP files cached in memory by the parser. Increasing this value uses more memory but can speed up analysis by avoiding re-parsing frequently accessed files.",
    "defaultValue": "256"
  },
  {
    "key": "cache.resolvedPhpDocBlockCacheCountMax",
    "section": "Caching",
    "summary": "Maximum number of resolved PHPDoc blocks cached in memory. PHPDoc resolution is expensive, so this cache improves performance. Increase this for very large codebases with many PHPDoc annotations.",
    "defaultValue": "2048"
  },
  {
    "key": "checkBenevolentUnionTypes",
    "section": "Stricter analysis",
    "summary": "PHPStan defines benevolent union types, such as array-key. Benevolent unions aren't checked strictly even at the highest level:",
    "defaultValue": "false"
  },
  {
    "key": "checkDynamicProperties",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports use of dynamic properties as undefined.",
    "defaultValue": "false"
  },
  {
    "key": "checkExplicitMixedMissingReturn",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports code paths with missing return statement in functions and methods with @return mixed PHPDoc.",
    "defaultValue": "false"
  },
  {
    "key": "checkFunctionNameCase",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports function and method calls with incorrect name case.",
    "defaultValue": "false"
  },
  {
    "key": "checkInternalClassCaseSensitivity",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports references to built-in classes with incorrect name case.",
    "defaultValue": "false"
  },
  {
    "key": "checkMissingCallableSignature",
    "section": "Vague typehints",
    "summary": "See PHPStan config reference section \"Vague typehints\"."
  },
  {
    "key": "checkMissingOverrideMethodAttribute",
    "section": "Stricter analysis",
    "summary": "When set to true, PHPStan reports missing #[\\Override] attribute above methods that override a method coming from their parent classes, implemented interfaces, or abstract method from a used trait.",
    "defaultValue": "false"
  },
  {
    "key": "checkMissingOverridePropertyAttribute",
    "section": "Stricter analysis",
    "summary": "Controls whether PHPStan reports missing #[\\Override] attribute on properties that override a parent class property. This is a PHP 8.5 feature.",
    "defaultValue": "null"
  },
  {
    "key": "checkStrictPrintfPlaceholderTypes",
    "section": "Stricter analysis",
    "summary": "Requires Bleeding Edge until PHPStan 3.0. It determines which value types are allowed to be passed to various placeholders in printf-like functions:",
    "defaultValue": "false",
    "availableIn": "2.1.29"
  },
  {
    "key": "checkTooWideParameterOutInProtectedAndPublicMethods",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports param-out typehints that could be narrowed down because some of the listed types are never returned from a public or protected method. For private methods PHPStan does this by default.",
    "defaultValue": "false",
    "availableIn": "2.1.23"
  },
  {
    "key": "checkTooWideReturnTypesInProtectedAndPublicMethods",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports return typehints that could be narrowed down because some of the listed types are never returned from a public or protected method. For private methods PHPStan does this by default.",
    "defaultValue": "false"
  },
  {
    "key": "checkTooWideThrowTypesInProtectedAndPublicMethods",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports @throws PHPDoc types that could be narrowed down because some of the listed exception types are never thrown from a public or protected method. For private methods and methods in final classes PHPStan does this by default.",
    "defaultValue": "false"
  },
  {
    "key": "checkUninitializedProperties",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports properties with native types that weren't initialized in the class constructor.",
    "defaultValue": "false"
  },
  {
    "key": "dynamicConstantNames",
    "section": "Constants",
    "summary": "See PHPStan config reference section \"Constants\"."
  },
  {
    "key": "earlyTerminatingFunctionCalls",
    "section": "Solving undefined variables",
    "summary": "See PHPStan config reference section \"Solving undefined variables\"."
  },
  {
    "key": "earlyTerminatingMethodCalls",
    "section": "Solving undefined variables",
    "summary": "See PHPStan config reference section \"Solving undefined variables\"."
  },
  {
    "key": "editorUrl",
    "section": "Clickable editor URL",
    "summary": "See PHPStan config reference section \"Clickable editor URL\"."
  },
  {
    "key": "editorUrlTitle",
    "section": "Clickable editor URL",
    "summary": "Customizes the link text shown for editor URLs in the table error formatter. Supports the same %file%, %relFile%, and %line% placeholders as editorUrl. When not set, the relative file path is used as the link text.",
    "defaultValue": "null"
  },
  {
    "key": "errorFormat",
    "section": "Miscellaneous parameters",
    "summary": "If you want to change the default error formatter, you can specify that using:",
    "defaultValue": "null"
  },
  {
    "key": "exceptions.check.missingCheckedExceptionInThrows",
    "section": "Exceptions",
    "summary": "When set to true, it reports missing @throws tags for checked exceptions above functions and methods. Requires configuring exceptions.checkedExceptionClasses or exceptions.checkedExceptionRegexes.",
    "defaultValue": "false"
  },
  {
    "key": "exceptions.check.throwTypeCovariance",
    "section": "Exceptions",
    "summary": "When set to true, it enforces that @throws types in overriding methods are covariant with the parent method's @throws types. A child method cannot declare broader exception types than its parent. This follows the Liskov Substitution Principle for exception declarations.",
    "defaultValue": "false"
  },
  {
    "key": "exceptions.check.tooWideImplicitThrowType",
    "section": "Exceptions",
    "summary": "When set to true, it extends throws.unusedType to also report too-wide @throws types that were inherited or implicitly inferred, not just those explicitly written in PHPDoc. By default, only explicitly written @throws types are checked.",
    "defaultValue": "false"
  },
  {
    "key": "exceptions.checkedExceptionClasses",
    "section": "Exceptions",
    "summary": "See PHPStan config reference section \"Exceptions\"."
  },
  {
    "key": "exceptions.checkedExceptionRegexes",
    "section": "Exceptions",
    "summary": "See PHPStan config reference section \"Exceptions\"."
  },
  {
    "key": "exceptions.implicitThrows",
    "section": "Exceptions",
    "summary": "When set to true (the default), a function or method without a @throws tag is assumed to potentially throw any exception. When set to false, absent @throws is interpreted as the function not throwing any exception. You can write @throws void to explicitly mark a function that doesn't throw.",
    "defaultValue": "true"
  },
  {
    "key": "exceptions.reportUncheckedExceptionDeadCatch",
    "section": "Exceptions",
    "summary": "When set to true (the default), PHPStan reports dead catch blocks for unchecked exceptions — catch blocks that can never be reached because the called code never throws that exception type. Set to false if you don't plan to annotate @throws tags for unchecked exceptions but still occasionally catch them.",
    "defaultValue": "true"
  },
  {
    "key": "exceptions.uncheckedExceptionClasses",
    "section": "Exceptions",
    "summary": "See PHPStan config reference section \"Exceptions\"."
  },
  {
    "key": "exceptions.uncheckedExceptionRegexes",
    "section": "Exceptions",
    "summary": "See PHPStan config reference section \"Exceptions\"."
  },
  {
    "key": "excludePaths",
    "section": "Analysed files",
    "summary": "See PHPStan config reference section \"Analysed files\"."
  },
  {
    "key": "fileExtensions",
    "section": "Analysed files",
    "summary": "See PHPStan config reference section \"Analysed files\"."
  },
  {
    "key": "ignoreErrors",
    "section": "Ignoring errors",
    "summary": "See PHPStan config reference section \"Ignoring errors\"."
  },
  {
    "key": "inferPrivatePropertyTypeFromConstructor",
    "section": "Miscellaneous parameters",
    "summary": "When set to true, it doesn't require typehints for properties if the types can be inferred from constructor injection:",
    "defaultValue": "false"
  },
  {
    "key": "internalErrorsCountLimit",
    "section": "Miscellaneous parameters",
    "summary": "The maximum number of internal errors (unexpected exceptions during analysis) before PHPStan stops the analysis. This prevents PHPStan from running indefinitely when encountering systemic issues.",
    "defaultValue": "50"
  },
  {
    "key": "level",
    "section": "Config file",
    "summary": "See PHPStan config reference section \"Config file\"."
  },
  {
    "key": "mixinExcludeClasses",
    "section": "Miscellaneous parameters",
    "summary": "A list of class names to exclude from @mixin resolution. Methods and properties from these mixin classes will not be available on classes that use them via @mixin.",
    "defaultValue": "[]"
  },
  {
    "key": "parallel.buffer",
    "section": "Parallel processing",
    "summary": "Sets the maximum buffer size in bytes for communication between the main process and worker processes during parallel analysis. You might need to increase this if you encounter issues with very large analysis results.",
    "defaultValue": "134217728"
  },
  {
    "key": "parallel.loadLimit",
    "section": "Parallel processing",
    "summary": "A percentage in the range [0.0, 1.0] representing the fraction of available CPU cores that PHPStan should use for parallel workers. The number of available cores is determined by the system load average — busy cores are subtracted from the total.",
    "defaultValue": "1.0"
  },
  {
    "key": "paths",
    "section": "Analysed files",
    "summary": "See PHPStan config reference section \"Analysed files\"."
  },
  {
    "key": "phpVersion",
    "section": "Miscellaneous parameters",
    "summary": "If you want to analyse a codebase as if it was written for a different PHP version than you're currently running, change the phpVersion parameter:",
    "defaultValue": "null"
  },
  {
    "key": "polluteScopeWithAlwaysIterableForeach",
    "section": "Stricter analysis",
    "summary": "When set to false it prevents reading key and value variables set in foreach when iterating over a non-empty array.",
    "defaultValue": "true"
  },
  {
    "key": "polluteScopeWithBlock",
    "section": "Stricter analysis",
    "summary": "When set to false it prevents reading key and value variables set in a separate code block in {...}.",
    "defaultValue": "true",
    "availableIn": "2.0"
  },
  {
    "key": "polluteScopeWithLoopInitialAssignments",
    "section": "Stricter analysis",
    "summary": "When set to false it prevents reading variables set in for loop initial statement and while loop condition after the loop.",
    "defaultValue": "true"
  },
  {
    "key": "pro.tmpDir",
    "section": "PHPStan Pro",
    "summary": "See PHPStan config reference section \"PHPStan Pro\"."
  },
  {
    "key": "propertyAlwaysReadTags",
    "section": "Miscellaneous parameters",
    "summary": "A list of PHPDoc tag strings. Properties annotated with any of these tags are considered always read, suppressing \"property is never read, only written\" errors from dead code detection.",
    "defaultValue": "[]"
  },
  {
    "key": "propertyAlwaysWrittenTags",
    "section": "Miscellaneous parameters",
    "summary": "A list of PHPDoc tag strings. Properties annotated with any of these tags are considered always written to, suppressing \"property is never written, only read\" errors from dead code detection. This is useful for properties managed by frameworks like Doctrine ORM.",
    "defaultValue": "[]"
  },
  {
    "key": "rememberPossiblyImpureFunctionValues",
    "section": "Stricter analysis",
    "summary": "By default, PHPStan considers all functions that return a value to be pure. That means that second call to the same function in the same scope will return the same narrowed type:",
    "defaultValue": "true"
  },
  {
    "key": "reportAlwaysTrueInLastCondition",
    "section": "Stricter analysis",
    "summary": "By default PHPStan does not report always true last condition in a series of elseif branches:",
    "defaultValue": "false"
  },
  {
    "key": "reportAnyTypeWideningInVarTag",
    "section": "Stricter analysis",
    "summary": "This option strictens checks used in reportWrongPhpDocTypeInVarTag. It strictly disallows any type widening. Compared to default behaviour, it disallows array key widening in inline PHPDoc @var tags, so those would get reported:",
    "defaultValue": "false"
  },
  {
    "key": "reportIgnoresWithoutComments",
    "section": "Ignoring errors",
    "summary": "When set to true, PHPStan reports @phpstan-ignore identifiers that don't have an accompanying comment in parentheses explaining why the error is being ignored. It also disallows @phpstan-ignore-line and @phpstan-ignore-next-line completely, because these don't support error identifiers and comments.",
    "defaultValue": "false",
    "availableIn": "2.1.41"
  },
  {
    "key": "reportMaybesInMethodSignatures",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports violations of parameter type contravariance and return type covariance. By default, PHPStan only reports completely incompatible types in signatures, see this example.",
    "defaultValue": "false"
  },
  {
    "key": "reportMaybesInPropertyPhpDocTypes",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports violations of property type invariance. By default, PHPStan only reports completely incompatible PHPDoc types, see this example.",
    "defaultValue": "false"
  },
  {
    "key": "reportNonIntStringArrayKey",
    "section": "Stricter analysis",
    "summary": "By default, PHPStan does not report when array keys are used that are neither integers nor strings at compile time:",
    "defaultValue": "false",
    "availableIn": "2.1.39"
  },
  {
    "key": "reportPossiblyNonexistentConstantArrayOffset",
    "section": "Stricter analysis",
    "summary": "By default PHPStan does not report possibly nonexistent offset on array shapes:"
  },
  {
    "key": "reportPossiblyNonexistentGeneralArrayOffset",
    "section": "Stricter analysis",
    "summary": "By default PHPStan does not report possibly nonexistent offset on general arrays:"
  },
  {
    "key": "reportStaticMethodSignatures",
    "section": "Stricter analysis",
    "summary": "When set to true, it reports violations of parameter type contravariance and return type covariance in static methods.",
    "defaultValue": "false"
  },
  {
    "key": "reportUnmatchedIgnoredErrors",
    "section": "Ignoring errors",
    "summary": "See PHPStan config reference section \"Ignoring errors\"."
  },
  {
    "key": "reportUnsafeArrayStringKeyCasting",
    "section": "Stricter analysis",
    "summary": "PHP silently casts array keys that look like decimal integers from string to int. This means array can't guarantee that keys are actually strings at runtime. Read more about this problem »",
    "defaultValue": "null",
    "availableIn": "2.2.0"
  },
  {
    "key": "reportWrongPhpDocTypeInVarTag",
    "section": "Stricter analysis",
    "summary": "By default PHPStan reports wrong type in @var tag only for native types on the right side of =. With reportWrongPhpDocTypeInVarTag set to true it will consider PHPDoc types too.",
    "defaultValue": "false"
  },
  {
    "key": "resultCacheChecksProjectExtensionFilesDependencies",
    "section": "Miscellaneous parameters",
    "summary": "When set to true, PHPStan tracks transitive dependencies of project extension files for cache invalidation. This adds overhead but catches more scenarios where the cache should be invalidated.",
    "defaultValue": "false"
  },
  {
    "key": "resultCachePath",
    "section": "Miscellaneous parameters",
    "summary": "The file path where PHPStan stores the result cache for incremental analysis.",
    "defaultValue": "%tmpDir%/resultCache.php"
  },
  {
    "key": "resultCacheSkipIfOlderThanDays",
    "section": "Miscellaneous parameters",
    "summary": "Forces a full re-analysis if the result cache is older than the specified number of days, ensuring PHPStan periodically performs a complete analysis.",
    "defaultValue": "7"
  },
  {
    "key": "scanDirectories",
    "section": "Discovering symbols",
    "summary": "See PHPStan config reference section \"Discovering symbols\"."
  },
  {
    "key": "scanFiles",
    "section": "Discovering symbols",
    "summary": "See PHPStan config reference section \"Discovering symbols\"."
  },
  {
    "key": "tips",
    "section": "Miscellaneous parameters",
    "summary": "If you want to turn off a tip that PHPStan shows, you can do this in the tips section:",
    "defaultValue": "true"
  },
  {
    "key": "tips.discoveringSymbols",
    "section": "Discovering symbols",
    "summary": "See PHPStan config reference section \"Discovering symbols\"."
  },
  {
    "key": "tipsOfTheDay",
    "section": "Miscellaneous parameters",
    "summary": "From time to time, PHPStan shows \"💡 Tips of the Day\" at the end of a successful analysis. You can turn this off by setting tipsOfTheDay key to false.",
    "defaultValue": "true"
  },
  {
    "key": "tmpDir",
    "section": "Caching",
    "summary": "See PHPStan config reference section \"Caching\"."
  },
  {
    "key": "treatPhpDocTypesAsCertain",
    "section": "Miscellaneous parameters",
    "summary": "PHPStan by default doesn't differentiate between PHPDoc and native types. It considers them both as certain.",
    "defaultValue": "true"
  },
  {
    "key": "universalObjectCratesClasses",
    "section": "Universal object crates",
    "summary": "See PHPStan config reference section \"Universal object crates\"."
  },
  {
    "key": "usePathConstantsAsConstantString",
    "section": "Miscellaneous parameters",
    "summary": "When set to true, the magic constants __FILE__ and __DIR__ are resolved to their literal file path values instead of being generalized to string. This enables rules that depend on exact path values, such as checking whether a file referenced by require actually exists.",
    "defaultValue": "false"
  }
] as const satisfies readonly PhpStanReferenceEntry[];

export const PHPSTAN_CONFIG_REFERENCE_BY_KEY = Object.freeze(
  Object.fromEntries(PHPSTAN_CONFIG_REFERENCE.map((entry) => [entry.key, entry])),
) as Readonly<Record<string, PhpStanReferenceEntry>>;
